$schema: "http://json.schemastore.org/prettierrc"
printWidth: 100
semi: false
singleQuote: false
trailingComma: "all"
arrowParens: "avoid"
bracketSameLine: true
bracketSpacing: true
eslintIntegration: true
